"""add event price, standard and vip

Revision ID: 9a318ff6e505
Revises: a53606ea9f71
Create Date: 2026-10-01 14:19:57.410394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a318ff6e505'
down_revision: Union[str, Sequence[str], None] = 'a53606ea9f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('standard_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('events', sa.Column('vip_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'vip_price')
    op.drop_column('events', 'standard_price')
    # ### end Alembic commands ###
