"""add event_seats, reservations

Revision ID: a53606ea9f71
Revises: 28a201120b9d
Create Date: 2026-09-28 13:00:41.065058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a53606ea9f71'
down_revision: Union[str, Sequence[str], None] = '28a201120b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation_items')
    op.create_index(op.f('ix_event_seats_hold_expires_at'), 'event_seats', ['hold_expires_at'], unique=False)
    op.create_index(op.f('ix_event_seats_reservation_id'), 'event_seats', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_event_seats_seat_id'), 'event_seats', ['seat_id'], unique=False)
    op.create_index('uq_event_seat_active_reservation', 'event_seats', ['event_id', 'seat_id'], unique=True, postgresql_where=sa.text('reservation_id IS NOT NULL'))
    op.drop_constraint(op.f('event_seats_seat_id_fkey'), 'event_seats', type_='foreignkey')
    op.create_foreign_key(None, 'event_seats', 'seats', ['seat_id'], ['id'], ondelete='CASCADE')
    op.drop_column('event_seats', 'status')
    op.create_index(op.f('ix_events_organizer_id'), 'events', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_events_starts_at'), 'events', ['starts_at'], unique=False)
    op.create_index(op.f('ix_events_venue_id'), 'events', ['venue_id'], unique=False)
    op.create_index(op.f('ix_reservations_event_id'), 'reservations', ['event_id'], unique=False)
    op.create_index(op.f('ix_reservations_expires_at'), 'reservations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    op.drop_constraint(op.f('reservations_event_id_fkey'), 'reservations', type_='foreignkey')
    op.drop_constraint(op.f('reservations_user_id_fkey'), 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'events', ['event_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'reservations', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('reservations', 'idempotency_key')
    op.drop_column('reservations', 'total_amount')
    op.create_index(op.f('ix_venues_owner_id'), 'venues', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venues_owner_id'), table_name='venues')
    op.add_column('reservations', sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('reservations', sa.Column('idempotency_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key(op.f('reservations_user_id_fkey'), 'reservations', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('reservations_event_id_fkey'), 'reservations', 'events', ['event_id'], ['id'])
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_expires_at'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_event_id'), table_name='reservations')
    op.drop_index(op.f('ix_events_venue_id'), table_name='events')
    op.drop_index(op.f('ix_events_starts_at'), table_name='events')
    op.drop_index(op.f('ix_events_organizer_id'), table_name='events')
    op.add_column('event_seats', sa.Column('status', postgresql.ENUM('AVAILABLE', 'HELD', 'SOLD', 'BLOCKED', name='event_seat_status'), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'event_seats', type_='foreignkey')
    op.create_foreign_key(op.f('event_seats_seat_id_fkey'), 'event_seats', 'seats', ['seat_id'], ['id'])
    op.drop_index('uq_event_seat_active_reservation', table_name='event_seats', postgresql_where=sa.text('reservation_id IS NOT NULL'))
    op.drop_index(op.f('ix_event_seats_seat_id'), table_name='event_seats')
    op.drop_index(op.f('ix_event_seats_reservation_id'), table_name='event_seats')
    op.drop_index(op.f('ix_event_seats_hold_expires_at'), table_name='event_seats')
    op.create_table('reservation_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reservation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_seat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_seat_id'], ['event_seats.id'], name=op.f('reservation_items_event_seat_id_fkey')),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('reservation_items_reservation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reservation_items_pkey')),
    sa.UniqueConstraint('reservation_id', 'event_seat_id', name=op.f('uq_reservation_item'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
